[tools]
rust = "stable"
shfmt = "latest"
uv = "latest"

[settings]
experimental = true
# use_file_shell_for_executable_tasks = true
# windows_default_file_shell_args = "mise/runtask.cmd"
# windows_executable_extensions = [ "exe", "bat", "cmd", "com", "ps1", "vbs", "py" ]
idiomatic_version_file_enable_tools = ["rust"]

[settings.python]
uv_venv_auto = true
